#!/usr/bin/env python3
"""ISO 3166-1 davlatlar katalogi (yurisdiksiya tanlovchisi uchun).

Manbalar (xotiradan emas):
* ISO 3166-1 alpha-2 kodlari — `pycountry` (iso-codes ma’lumotlar to‘plami);
* EN / RU / UZ nomlar — Unicode CLDR (`babel`).
Bu faqat **nom katalogi**: unda hech qanday huquqiy ma’lumot yo‘q.
Ishga tushirish: apps/mobile ichida `python3 tool/gen_country_directory.py`.
"""
import babel
import pycountry
from babel import Locale

OUT = "lib/domain/jurisdiction/country_directory.g.dart"
L = {code: Locale.parse(code).territories for code in ("en", "ru", "uz")}


def name(lang, cc, fallback):
    n = L[lang].get(cc) or fallback
    # Ilova standarti: o‘zbek apostrofi ‘ (U+2018).
    return n.replace("ʻ", "‘").replace("'", "’") if lang == "uz" else n.replace("'", "’")


def q(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


rows = []
for c in sorted(pycountry.countries, key=lambda c: c.alpha_2):
    cc = c.alpha_2
    rows.append(f"  CountryName({q(cc)}, {q(name('en', cc, c.name))}, {q(name('ru', cc, c.name))}, "
                f"{q(name('uz', cc, c.name))}),")

open(OUT, "w").write(f"""// GENERATED by tool/gen_country_directory.py — qo‘lda o‘zgartirmang.
// ISO 3166-1 (pycountry {pycountry.__version__ if hasattr(pycountry, '__version__') else ''}) +
// Unicode CLDR nomlari (babel {babel.__version__}). Faqat nomlar — huquqiy ma’lumot emas.
// ignore_for_file: lines_longer_than_80_chars

part of 'country_directory.dart';

const _countries = <CountryName>[
{chr(10).join(rows)}
];
""")
print(len(rows), "countries")
