# PHASE 8–12 lokalizatsiya kalitlari. RU/UZ — mashina qoralamasi (RG-11).
import json, collections
D = "lib/core/l10n/arb"
K = collections.OrderedDict()
def k(key, desc, en, ru, uz, ph=None):
    K[key] = (desc, en, ru, uz, ph)
S = {"type": "String"}
I = {"type": "int"}

# --- PHASE 8: reagent / ekspress test / metod --------------------------------
k("reagentConcentration","Recipe field.","Concentration","Концентрация","Konsentratsiya")
k("reagentSolvent","Recipe field.","Solvent","Растворитель","Erituvchi")
k("reagentPh","Recipe field.","pH","pH","pH")
k("reagentExpiry","Recipe field.","Expiry / shelf life","Срок годности","Yaroqlilik muddati")
k("reagentHazards","Recipe field.","Hazard","Опасность","Xavf")
k("reagentPpe","Recipe field.","Personal protective equipment","Средства индивидуальной защиты","Shaxsiy himoya vositalari")
k("screeningResultType","Screening field.","Result type (qualitative / semi-quantitative)","Тип результата (качественный / полуколичественный)","Natija turi (sifat / yarim miqdoriy)")
k("screeningDetectionWindow","Screening field.","Detection window (context-dependent)","Окно обнаружения (зависит от условий)","Aniqlash oynasi (sharoitga bog‘liq)")
k("screeningInterference","Screening field.","Interference","Интерференция","Interferensiya")
k("evInternationalStandard","Method evidence type.","International standard","Международный стандарт","Xalqaro standart")
k("evGuideline","Method evidence type.","Guideline","Руководство","Qo‘llanma")
k("evPublishedValidated","Method evidence type.","Published validated method","Опубликованный валидированный метод","Nashr etilgan validatsiyalangan metod")
k("evNationalMethod","Method evidence type.","National method","Национальная методика","Milliy metodika")
k("evLocalSop","Method evidence type.","Local SOP reference","Ссылка на локальную СОП","Mahalliy SOP havolasi")
k("evEducationalSummary","Method evidence type.","Educational summary","Учебное обобщение","Ta’limiy umumlashma")

k("disciplineSourcedTopics","Section.","Sourced topics","Темы с источниками","Manbali mavzular")

# --- PHASE 9: AI / RAG ---------------------------------------------------
k("aiRagAnswer","Section.","Answer","Ответ","Javob")
k("aiRagJurisdictionNotApplicable","Value.","Not a legal question — no jurisdiction applied","Не правовой вопрос — юрисдикция не применяется","Huquqiy savol emas — yurisdiksiya qo‘llanmadi")
k("aiLimNotVerified","Limitation.","Evidence is not yet verified by qualified human reviewers.","Данные ещё не проверены квалифицированными рецензентами.","Dalillar hali malakali reviewerlar tomonidan tasdiqlanmagan.")
k("aiLimConflict","Limitation.","Sources disagree or overlap — see EVIDENCE CONFLICT.","Источники расходятся или перекрываются — см. ПРОТИВОРЕЧИЕ ДАННЫХ.","Manbalar mos kelmaydi yoki ustma-ust tushadi — DALILLAR ZIDDIYATI ga qarang.")
k("aiLimRetracted","Limitation.","{n} statement(s) from retracted or superseded sources were excluded.","Исключено утверждений из отозванных или заменённых источников: {n}.","Retraksiya qilingan yoki almashtirilgan manbalardan {n} ta da’vo chiqarib tashlandi.",{"n":I})
k("aiLimExpert","Limitation.","Interpretation of an individual case requires a qualified expert.","Интерпретация конкретного случая требует квалифицированного эксперта.","Muayyan holatni talqin qilish malakali ekspertni talab qiladi.")
k("aiLimMock","Limitation.","Generated by a TEST provider — not a production AI service.","Сгенерировано ТЕСТОВЫМ провайдером — не рабочий ИИ-сервис.","TEST provayderi yaratgan — ishchi AI xizmati emas.")

# --- PHASE 10: law & jurisdiction -----------------------------------------
k("instrOriginalTitle","Instrument field.","Original title","Оригинальное название","Asl nomi")
k("legalMissingFields","Banner.","Not recorded for this document: {fields}","Для этого документа не указано: {fields}","Bu hujjat uchun ko‘rsatilmagan: {fields}",{"fields":S})
k("lfOfficialTitle","Field.","Official title","Официальное название","Rasmiy nomi")
k("lfOriginalTitle","Field.","Original-language title","Название на языке оригинала","Asl tildagi nomi")
k("lfArticle","Field.","Article / section","Статья / раздел","Modda / bo‘lim")
k("lfOfficialUrl","Field.","Official URL","Официальная ссылка","Rasmiy havola")
k("lfReviewStatus","Field.","Review status","Статус проверки","Tekshiruv holati")
k("legalDomainsTitle","Section.","Legal domains","Правовые области","Huquqiy sohalar")
k("legalDomainRecords","Count.","{n} records","Записей: {n}","{n} ta yozuv",{"n":I})
k("legalDomainNoContent","Value.","No verified content","Нет проверенного содержания","Tasdiqlangan kontent yo‘q")
k("compareTopicControlStatus","Compare topic.","Control status","Статус контроля","Nazorat holati")
k("ldExpertStatus","Legal domain.","Forensic expert status","Статус судебного эксперта","Sud eksperti maqomi")
k("ldEvidenceHandling","Legal domain.","Evidence handling","Обращение с доказательствами","Dalillar bilan ishlash")
k("ldChainOfCustody","Legal domain.","Chain of custody","Цепочка хранения","Saqlash zanjiri")
k("ldSpecimenCollection","Legal domain.","Specimen collection","Отбор образцов","Namuna olish")
k("ldDeathInvestigation","Legal domain.","Death investigation","Расследование смерти","O‘limni tekshirish")
k("ldAutopsy","Legal domain.","Autopsy","Вскрытие","Yorib ko‘rish (autopsiya)")
k("ldToxicology","Legal domain.","Toxicology","Токсикология","Toksikologiya")
k("ldAlcoholDriving","Legal domain.","Alcohol and driving","Алкоголь и вождение","Alkogol va transport boshqarish")
k("ldControlledSubstances","Legal domain.","Controlled substances","Контролируемые вещества","Nazorat ostidagi moddalar")
k("ldReporting","Legal domain.","Reporting","Отчётность","Hisobot berish")
k("ldLaboratoryStandards","Legal domain.","Laboratory standards","Лабораторные стандарты","Laboratoriya standartlari")
k("ldRetentionStorage","Legal domain.","Retention and storage","Хранение","Saqlash muddatlari")
k("ldTestimony","Legal domain.","Testimony","Показания в суде","Sudda ko‘rsatma berish")
k("ldQualityAccreditation","Legal domain.","Quality and accreditation","Качество и аккредитация","Sifat va akkreditatsiya")

# --- PHASE 11: data deletion -----------------------------------------------
k("deleteLocalData","Profile action.","Delete data on this device","Удалить данные на этом устройстве","Qurilmadagi ma’lumotlarni o‘chirish")
k("deleteLocalDataConfirm","Button.","Delete","Удалить","O‘chirish")
k("deleteLocalDataDone","Snackbar.","Local data deleted","Локальные данные удалены","Qurilmadagi ma’lumotlar o‘chirildi")

for idx, code in enumerate(["en","ru","uz"]):
    p = f"{D}/app_{code}.arb"
    data = json.load(open(p, encoding="utf-8"), object_pairs_hook=collections.OrderedDict)
    for key,(desc,en,ru,uz,ph) in K.items():
        data[key] = (en,ru,uz)[idx]
        if code == "en":
            meta = {"description": desc}
            if ph: meta["placeholders"] = ph
            data["@"+key] = meta
    json.dump(data, open(p,"w",encoding="utf-8"), ensure_ascii=False, indent=2)
    open(p,"a").write("\n")
print(len(K), "keys")
