# PHASE 8–12 lokalizatsiya kalitlari. RU/UZ — mashina qoralamasi (RG-11).
import json, collections
D = "lib/core/l10n/arb"
K = collections.OrderedDict()
def k(key, desc, en, ru, uz, ph=None):
    K[key] = (desc, en, ru, uz, ph)
S = {"type": "String"}
I = {"type": "int"}

# --- PHASE 8: reagent / ekspress test / metod --------------------------------
k("reagentConcentration","Recipe field.","Concentration","Концентрация","Konsentratsiya")
k("reagentSolvent","Recipe field.","Solvent","Растворитель","Erituvchi")
k("reagentPh","Recipe field.","pH","pH","pH")
k("reagentExpiry","Recipe field.","Expiry / shelf life","Срок годности","Yaroqlilik muddati")
k("reagentHazards","Recipe field.","Hazard","Опасность","Xavf")
k("reagentPpe","Recipe field.","Personal protective equipment","Средства индивидуальной защиты","Shaxsiy himoya vositalari")
k("screeningResultType","Screening field.","Result type (qualitative / semi-quantitative)","Тип результата (качественный / полуколичественный)","Natija turi (sifat / yarim miqdoriy)")
k("screeningDetectionWindow","Screening field.","Detection window (context-dependent)","Окно обнаружения (зависит от условий)","Aniqlash oynasi (sharoitga bog‘liq)")
k("screeningInterference","Screening field.","Interference","Интерференция","Interferensiya")
k("evInternationalStandard","Method evidence type.","International standard","Международный стандарт","Xalqaro standart")
k("evGuideline","Method evidence type.","Guideline","Руководство","Qo‘llanma")
k("evPublishedValidated","Method evidence type.","Published validated method","Опубликованный валидированный метод","Nashr etilgan validatsiyalangan metod")
k("evNationalMethod","Method evidence type.","National method","Национальная методика","Milliy metodika")
k("evLocalSop","Method evidence type.","Local SOP reference","Ссылка на локальную СОП","Mahalliy SOP havolasi")
k("evEducationalSummary","Method evidence type.","Educational summary","Учебное обобщение","Ta’limiy umumlashma")

k("disciplineSourcedTopics","Section.","Sourced topics","Темы с источниками","Manbali mavzular")

# --- PHASE 9: AI / RAG ---------------------------------------------------
k("aiRagAnswer","Section.","Answer","Ответ","Javob")
k("aiRagJurisdictionNotApplicable","Value.","Not a legal question — no jurisdiction applied","Не правовой вопрос — юрисдикция не применяется","Huquqiy savol emas — yurisdiksiya qo‘llanmadi")
k("aiLimNotVerified","Limitation.","Evidence is not yet verified by qualified human reviewers.","Данные ещё не проверены квалифицированными рецензентами.","Dalillar hali malakali reviewerlar tomonidan tasdiqlanmagan.")
k("aiLimConflict","Limitation.","Sources disagree or overlap — see EVIDENCE CONFLICT.","Источники расходятся или перекрываются — см. ПРОТИВОРЕЧИЕ ДАННЫХ.","Manbalar mos kelmaydi yoki ustma-ust tushadi — DALILLAR ZIDDIYATI ga qarang.")
k("aiLimRetracted","Limitation.","{n} statement(s) from retracted or superseded sources were excluded.","Исключено утверждений из отозванных или заменённых источников: {n}.","Retraksiya qilingan yoki almashtirilgan manbalardan {n} ta da’vo chiqarib tashlandi.",{"n":I})
k("aiLimExpert","Limitation.","Interpretation of an individual case requires a qualified expert.","Интерпретация конкретного случая требует квалифицированного эксперта.","Muayyan holatni talqin qilish malakali ekspertni talab qiladi.")
k("aiLimMock","Limitation.","Generated by a TEST provider — not a production AI service.","Сгенерировано ТЕСТОВЫМ провайдером — не рабочий ИИ-сервис.","TEST provayderi yaratgan — ishchi AI xizmati emas.")

for idx, code in enumerate(["en","ru","uz"]):
    p = f"{D}/app_{code}.arb"
    data = json.load(open(p, encoding="utf-8"), object_pairs_hook=collections.OrderedDict)
    for key,(desc,en,ru,uz,ph) in K.items():
        data[key] = (en,ru,uz)[idx]
        if code == "en":
            meta = {"description": desc}
            if ph: meta["placeholders"] = ph
            data["@"+key] = meta
    json.dump(data, open(p,"w",encoding="utf-8"), ensure_ascii=False, indent=2)
    open(p,"a").write("\n")
print(len(K), "keys")
