#!/usr/bin/env bash
# Pilot kontent paketini qayta yig‘ib, ilovaga asset sifatida joylaydi.
#
# 1. content/pilot/bundle.json → validator → content.db → imzo
#    (development kanal; vaqtinchalik kalit, maxfiy kalit saqlanmaydi);
# 2. paket apps/mobile/assets/content/pilot/ ga ko‘chiriladi;
# 3. ochiq kalit ilova KODIGA yoziladi (lib/data/content/trusted_keys.g.dart).
#    Ilova kalitni paket yonidagi fayldan EMAS, kompilyatsiya qilingan
#    koddan oladi — asset almashtirilsa imzo tekshiruvi uni rad etadi.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=build/content_pack
DEST=apps/mobile/assets/content/pilot
dart run fe_content_pipeline:build_pack --input content/pilot/bundle.json --out "$OUT"
mkdir -p "$DEST"
cp "$OUT/content.db" "$OUT/manifest.json" "$OUT/manifest.sig" "$DEST/"

python3 - "$OUT/signing_public_key.json" > apps/mobile/lib/data/content/trusted_keys.g.dart <<'PY'
import json, sys
k = json.load(open(sys.argv[1]))
print("// GENERATED by tool/update_bundled_pack.sh — qo‘lda o‘zgartirmang.")
print("//")
print("// Faqat OCHIQ kalit. Development kanal kaliti har yig‘ishda yangilanadi;")
print("// production kaliti alohida (RG-17) va bu faylga hech qachon tushmaydi.")
print("")
print("/// Ilovaga o‘rnatilgan pilot paketni tekshiruvchi ochiq kalitlar.")
print("const bundledPackTrustedKeys = <String, String>{")
print(f"  '{k['key_id']}': '{k['public_key_base64']}',")
print("};")
PY
dart format apps/mobile/lib/data/content/trusted_keys.g.dart >/dev/null
echo "Bundled pack updated: $(python3 -c "import json;print(json.load(open('$DEST/manifest.json'))['pack_version'])")"
