import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter_test/flutter_test.dart';
import 'package:forensic_expert/domain/guidelines/guideline_models.dart';
import 'package:forensic_expert/domain/learn/study_models.dart';

import '../helpers/pilot_content.dart';

/// O‘quv testi qayta qurilishi (Phase E) — HAQIQIY kontent bo‘yicha:
/// distraktorlar faqat bir soha ichida, izoh har savolda, imtihonga faqat
/// mos elementlar. Statistika `--reporter expanded` bilan chop etiladi.
void main() {
  late StudyCatalog catalog;
  late List<StudyItem> items;

  setUpAll(() async {
    final pilot = await loadPilotContent();
    final guidelines = GuidelineBundle.fromJson(
      (jsonDecode(
        File('assets/content/guidelines/guidelines_v1.json').readAsStringSync(),
      ) as Map).cast<String, Object?>(),
    );
    catalog = StudyCatalogBuilder.build(
      knowledge: pilot.knowledge,
      library: pilot.library,
      guidelines: guidelines,
      substancesUnlocked: true,
      referencesUnlocked: true,
    );
    items = [for (final d in catalog.decks) ...d.items];
  });

  test('statistika (hisobot uchun)', () {
    final byFormat = <StudyQuizFormat, int>{};
    for (final i in items) {
      byFormat.update(catalog.formatOf(i), (v) => v + 1, ifAbsent: () => 1);
    }
    final lines = <String>[
      'items=${items.length} decks=${catalog.decks.length}',
      'formats=${{for (final e in byFormat.entries) e.key.name: e.value}}',
      for (final lang in const ['uz', 'ru', 'en'])
        'exam[$lang]=${items.where((i) => StudyEligibility.examEligible(i, lang)).length}',
      'smallest deck=${catalog.decks.map((d) => d.items.length).reduce(min)}',
      for (final d in catalog.decks)
        '  ${d.id}: ${d.items.length} '
            'mc=${d.items.where((i) => catalog.formatOf(i) == StudyQuizFormat.multipleChoice).length} '
            'tf=${d.items.where((i) => catalog.formatOf(i) == StudyQuizFormat.trueFalse).length} '
            'card=${d.items.where((i) => catalog.formatOf(i) == StudyQuizFormat.flashcardOnly).length} '
            'exam.uz=${StudyQuizBuilder.examCount(d, catalog, 'uz')}',
    ];
    // ignore: avoid_print
    print(lines.join('\n'));
    expect(items.length, greaterThan(250));
  });

  test('distraktorlar hech qachon boshqa fan/sohadan emas', () {
    for (final d in catalog.decks) {
      for (var seed = 0; seed < 5; seed++) {
        for (final q in StudyQuizBuilder.build(
          d,
          catalog,
          seed: seed,
          length: 500,
        )) {
          if (q.item.distractors.isNotEmpty) continue;
          for (final o in q.options) {
            expect(o.domain, q.item.domain, reason: '${q.item.id} ← ${o.id}');
            expect(o.domain, isNotEmpty, reason: q.item.id);
          }
        }
      }
    }
  });

  test('har bir test savolida uch tilda izoh va manba bor', () {
    for (final d in catalog.decks) {
      for (final q in StudyQuizBuilder.build(
        d,
        catalog,
        seed: 1,
        length: 500,
      )) {
        for (final lang in const ['uz', 'ru', 'en']) {
          expect(q.item.hasExplanation(lang), isTrue, reason: q.item.id);
        }
      }
    }
    // 76 muallif savolining hammasida izoh bor.
    final authored = [
      for (final i in items)
        if (i.kind == StudyItemKind.guidelineQuestion) i,
    ];
    expect(authored, hasLength(76));
    for (final i in authored) {
      for (final lang in const ['uz', 'ru', 'en']) {
        expect(i.explanation?.values[lang], isNotEmpty, reason: i.id);
      }
      expect(i.citations.every((c) => c.hasLocator), isTrue, reason: i.id);
    }
  });

  test('imtihon: faqat mos elementlar; ru/en qoralama — imtihonsiz', () {
    final uz = items.where((i) => StudyEligibility.examEligible(i, 'uz'));
    expect(uz.length, 76);
    expect(uz.every((i) => i.kind == StudyItemKind.guidelineQuestion), isTrue);
    for (final lang in const ['ru', 'en']) {
      expect(
        items.where((i) => StudyEligibility.examEligible(i, lang)),
        isEmpty,
        reason: 'ru/en tarjimasi DRAFT — imtihonga kirmaydi',
      );
    }
    for (final i in items.where((i) => i.distractors.isEmpty)) {
      expect(
        StudyEligibility.reason(i, 'uz'),
        StudyIneligibility.autoGenerated,
      );
    }
    for (final d in catalog.decks) {
      for (final q in StudyQuizBuilder.build(
        d,
        catalog,
        seed: 3,
        mode: StudyQuizMode.exam,
        lang: 'uz',
      )) {
        expect(StudyEligibility.examEligible(q.item, 'uz'), isTrue);
        expect(q.format, StudyQuizFormat.multipleChoice);
      }
    }
  });

  test('bitta elementli to‘plam yo‘q; kichiklari aralash to‘plamda', () {
    for (final d in catalog.decks) {
      if (d.isMixed) continue;
      expect(
        d.items.length,
        greaterThanOrEqualTo(StudyCatalogBuilder.minDeckSize),
        reason: d.id,
      );
    }
  });
}
