#!/usr/bin/env python3
"""R2 geometriyasini SVG’dan Flutter painter uchun Dart konstantalariga
ko‘chiradi (qo‘lda nusxalash yo‘q — SVG yagona manba).

Ishga tushirish (repo ildizidan):
  python3 design/logo/refined/tools/export_flutter_geometry.py
"""
import re

SVG = "design/logo/refined/svg"
OUT = "apps/mobile/lib/core/widgets/brand_mark_r2.g.dart"


def paths(svg):
    return re.findall(r'<path d="([^"]+)"', svg)


def pts(d):
    nums = [float(x) for x in re.findall(r"-?\d+\.?\d*", d)]
    return list(zip(nums[0::2], nums[1::2]))


def dart_list(name, p):
    body = ", ".join(f"Offset({x:.2f}, {y:.2f})" for x, y in p)
    return f"const {name} = <Offset>[{body}];\n"


large = open(f"{SVG}/R2-integrated-peak-light.svg").read()
small = open(f"{SVG}/R2-integrated-peak-icon-small.svg").read()
lp = paths(large)
sp = paths(small)
# light: [mask-peak, mask-base, mask-drop, AREA, PEAK, BASE, DROP, TICK]
area, peak = pts(lp[3])[1:], pts(lp[4])
s_area, s_peak = pts(sp[0])[1:], pts(sp[1])
drop = pts(lp[6])
s_drop = pts(sp[3])

out = [
    "// GENERATED by design/logo/refined/tools/export_flutter_geometry.py.\n",
    "// Manba: design/logo/refined/svg/R2-integrated-peak-*.svg (100×100 grid).\n",
    "// R2 — egasi tanlagan yo‘nalish; trademark tekshiruvi kutilmoqda (RG-06).\n\n",
    "import 'dart:ui';\n\n",
    dart_list("r2PeakLarge", peak),
    dart_list("r2AreaLarge", area),
    f"const r2DropLarge = (Offset({drop[0][0]:.2f}, {drop[0][1]:.2f}), "
    f"Offset({drop[1][0]:.2f}, {drop[1][1]:.2f}));\n",
    dart_list("r2PeakSmall", s_peak),
    dart_list("r2AreaSmall", s_area),
    f"const r2DropSmall = (Offset({s_drop[0][0]:.2f}, {s_drop[0][1]:.2f}), "
    f"Offset({s_drop[1][0]:.2f}, {s_drop[1][1]:.2f}));\n",
]
open(OUT, "w").write("".join(out))
print("written", OUT, len(peak), len(area), len(s_peak), len(s_area))
