"""Entries part 4: volatile poisons, gases, metals, strychnine, organophosphorus pesticides.

Teaching complex = Yuldashev Z.A., Umarova G.Q. (2025); printed page == PDF page.
The source's own classification of reactions is kept: «negative value» means that only a
negative result is conclusive (a positive one proves nothing); this is stated per entry.
"""
from sm_core import N, colour, generic, loc, micro, tlc, tlc_free, uv
from substance_methods_data import E, add

NEG = N(
    "The source gives this reaction a negative forensic-chemical value: only a negative result is informative, a positive one is not proof.",
    "Manba bu reaksiyaga manfiy sud-kimyoviy ahamiyat beradi: faqat manfiy natija ma’lumotli, musbat natija isbot emas.",
    "Источник придаёт этой реакции отрицательное судебно-химическое значение: информативен только отрицательный результат, положительный не является доказательством.",
)


def neg_plus(extra):
    return N(extra[0] + " " + NEG[0], extra[1] + " " + NEG[1], extra[2] + " " + NEG[2])


# =============================================================== ETHANOL / METHANOL / ACETONE / CHLOROFORM
add(generic("ethanol", "chemical",
            N("Distillate tests: iodoform reaction (iodine in alkali) — yellow turbidity with a characteristic odour and, under the microscope, hexagonal yellow star-shaped crystals; oxidation with potassium dichromate and sulfuric acid — acetaldehyde odour and green colour; heating with sodium acetate and concentrated sulfuric acid — ethyl acetate odour; benzoyl chloride in alkali — a characteristic odour. The source gives the iodoform reaction a negative value, because other substances in the body also give it.",
              "Distillyatdagi sinamalar: yodoform reaksiyasi (yodning ishqordagi eritmasi) — sariq loyqa, xarakterli hid va mikroskopda olti qirrali sariq yulduzchalar shaklidagi kristallar; kaliy dixromat va sulfat kislota bilan oksidlash — sirka aldegidi hidi va yashil rang; natriy atsetat va konsentrlangan sulfat kislota bilan qizdirish — etilatsetat hidi; ishqoriy muhitda benzoilxlorid — xarakterli hid. Manba yodoform reaksiyasiga manfiy ahamiyat beradi, chunki uni organizmdagi boshqa moddalar ham beradi.",
              "Пробы с дистиллятом: иодоформная реакция (иод в щёлочи) — жёлтая муть с характерным запахом и под микроскопом шестиугольные жёлтые звёздчатые кристаллы; окисление дихроматом калия и серной кислотой — запах ацетальдегида и зелёный цвет; нагревание с ацетатом натрия и концентрированной серной кислотой — запах этилацетата; бензоилхлорид в щёлочи — характерный запах. Источник придаёт иодоформной реакции отрицательное значение, так как её дают и другие вещества в организме."),
            "TOKS", loc("TOKS", pdf=42), "presumptive", "presumptive",
            recipes=["recipe-potassium-dichromate-solution"], reagents=["iodoform reaction", "potassium dichromate"]))
add(generic("ethanol", "instrumental",
            N("The source names gas–liquid chromatography as the method for quantitative determination of ethanol (other listed procedures: ethyl nitrite method, Widmark–Shaimoshu method, Karantaev photocolorimetric method).",
              "Manba etanolni miqdoriy aniqlash usuli sifatida gaz-suyuqlik xromatografiyasini ko‘rsatadi (boshqa sanab o‘tilgan usullar: etilnitrit usuli, Vidmark–Shaymosh usuli, Karantaev fotokolorimetrik usuli).",
              "Источник называет газожидкостную хроматографию методом количественного определения этанола (другие перечисленные методики: этилнитритный, Видмарка—Шеймоша, фотоколориметрический по Карантаеву)."),
            "TOKS", loc("TOKS", pdf=43), "instrumental", "instrumental", cat="B", data={"methods": ["method-gc-fid", "method-headspace-gc"]}))
add(generic("methanol", "chemical",
            N("Distillate tests: heating with salicylic acid and concentrated sulfuric acid gives the odour of methyl salicylate (ethanol gives a similar odour, so the test is meaningful only when ethanol is absent); oxidation with potassium permanganate to formaldehyde, which is detected with fuchsin–sulfurous acid (pink-violet colour).",
              "Distillyatdagi sinamalar: salitsil kislota va konsentrlangan sulfat kislota bilan qizdirilganda metilsalitsilat hidi chiqadi (etanol ham o‘xshash hid beradi, shuning uchun sinama faqat etanol bo‘lmaganda ma’noga ega); kaliy permanganat bilan formaldegidgacha oksidlash va uni fuksin–sulfit kislota bilan aniqlash (pushti-binafsha rang).",
              "Пробы с дистиллятом: нагревание с салициловой и концентрированной серной кислотами даёт запах метилсалицилата (этанол даёт сходный запах, поэтому проба значима только при отсутствии этанола); окисление перманганатом калия до формальдегида, который определяют фуксинсернистой кислотой (розово-фиолетовая окраска)."),
            "TOKS", loc("TOKS", pdf=40, to=41), "presumptive", "presumptive",
            recipes=["recipe-fuchsin-sulfurous-acid"], reagents=["salicylic acid with sulfuric acid", "potassium permanganate, fuchsin–sulfurous acid"]))
add(generic("methanol", "instrumental",
            N("The source names gas–liquid chromatography for the quantitative determination of methanol, and photocolorimetry of the fuchsin–sulfurous acid colour after oxidation to formaldehyde as the alternative.",
              "Manba metanolni miqdoriy aniqlash uchun gaz-suyuqlik xromatografiyasini, muqobil sifatida formaldegidgacha oksidlashdan keyingi fuksin–sulfit kislota rangini fotokolorimetrik aniqlashni ko‘rsatadi.",
              "Источник называет для количественного определения метанола газожидкостную хроматографию, а альтернативой — фотоколориметрию окраски с фуксинсернистой кислотой после окисления до формальдегида."),
            "TOKS", loc("TOKS", pdf=41), "instrumental", "instrumental", cat="B", data={"methods": ["method-headspace-gc", "method-gc-fid"]}))
add(generic("acetone", "chemical",
            N("Distillate tests: sodium nitroprusside in alkali — red-violet colour (not specific: acetaldehyde, methyl ethyl ketone, acetophenone and others interfere); o-nitrobenzaldehyde in 2 N alkali — blue (indigo), extractable into chloroform, with small amounts first yellow, then yellow-green, then green-blue; the iodoform reaction is sensitive but not characteristic (ethanol and lactic acid also give it).",
              "Distillyatdagi sinamalar: natriy nitroprussid (ishqoriy muhitda) — qizil-binafsha rang (xos emas: sirka aldegidi, metiletilketon, atsetofenon va boshqalar halaqit beradi); o‘-nitrobenzaldegid (2 n ishqorda) — ko‘k (indigo), xloroformga o‘tadi, oz miqdorda avval sariq, so‘ng sariq-yashil, so‘ng yashil-ko‘k; yodoform reaksiyasi sezgir, lekin xarakterli emas (etanol va sut kislota ham beradi).",
              "Пробы с дистиллятом: нитропруссид натрия в щёлочи — красно-фиолетовый цвет (не специфично: мешают ацетальдегид, метилэтилкетон, ацетофенон и др.); о-нитробензальдегид в 2 н щёлочи — синий (индиго), переходит в хлороформ, при малых количествах сначала жёлтый, затем жёлто-зелёный, затем зелёно-синий; иодоформная реакция чувствительна, но не характерна (её дают также этанол и молочная кислота)."),
            "TOKS", loc("TOKS", pdf=33, to=34), "presumptive", "presumptive", reagents=["sodium nitroprusside", "o-nitrobenzaldehyde"]))
add(generic("acetone", "instrumental",
            N("The source states that acetone can be determined by gas–liquid chromatography with a flame-ionisation detector (by retention parameters) and quantified by the same method. It also notes that acetone is formed in the healthy body and in diabetes and can be a metabolite of isopropanol, which affects interpretation.",
              "Manba atsetonni alanga-ionlanish detektorli gaz-suyuqlik xromatografiyasi bilan (ushlanish parametrlari bo‘yicha) aniqlash va xuddi shu usulda miqdoriy aniqlash mumkinligini bildiradi. Shuningdek, aseton sog‘lom organizmda va diabetda hosil bo‘lishini va izopropanol metaboliti bo‘lishi mumkinligini ta’kidlaydi, bu talqinga ta’sir qiladi.",
              "Источник указывает, что ацетон можно определять газожидкостной хроматографией с пламенно-ионизационным детектором (по параметрам удерживания) и количественно определять тем же методом. Он также отмечает, что ацетон образуется в здоровом организме и при диабете и может быть метаболитом изопропанола, что влияет на интерпретацию."),
            "TOKS", loc("TOKS", pdf=33, to=34), "instrumental", "instrumental", cat="B", data={"methods": ["method-gc-fid", "method-headspace-gc"]}))
add(generic("chloroform", "chemical",
            N("Distillate tests: heating with alcoholic alkali then silver nitrate in nitric acid — white precipitate (given by all chlorine-containing compounds); isocyanide (carbylamine) test with aniline and alkali — foul odour (chloroform, carbon tetrachloride and chloral hydrate react, dichloroethane does not); alkaline resorcinol on heating — red colour (also chloral hydrate, carbon tetrachloride and formaldehyde, not dichloroethane); Fujiwara reaction (pyridine, alkali, heat) — red colour; Fehling solution on heating — yellow then red precipitate (chloroform and chloral hydrate react, carbon tetrachloride and dichloroethane do not).",
              "Distillyatdagi sinamalar: spirtli ishqor bilan qizdirib, so‘ng nitrat kislotali muhitda kumush nitrat — oq cho‘kma (barcha xlor saqlovchi birikmalar beradi); anilin va ishqor bilan izonitril (karbilamin) sinamasi — badbo‘y hid (xloroform, to‘rtxlorli uglerod va xloralgidrat reaksiyaga kirishadi, dixloretan kirishmaydi); ishqoriy rezorsin (qizdirilganda) — qizil rang (xloralgidrat, to‘rtxlorli uglerod va formaldegid ham beradi, dixloretan bermaydi); Fudjivara reaksiyasi (piridin, ishqor, qizdirish) — qizil rang; Feling suyuqligi (qizdirilganda) — avval sariq, so‘ng qizil cho‘kma (xloroform va xloralgidrat beradi, to‘rtxlorli uglerod va dixloretan bermaydi).",
              "Пробы с дистиллятом: нагревание со спиртовой щёлочью, затем нитрат серебра в азотнокислой среде — белый осадок (дают все хлорсодержащие соединения); изонитрильная (карбиламиновая) проба с анилином и щёлочью — неприятный запах (реагируют хлороформ, четырёххлористый углерод и хлоралгидрат, дихлорэтан не реагирует); щелочной резорцин при нагревании — красный цвет (также хлоралгидрат, четырёххлористый углерод и формальдегид, дихлорэтан нет); реакция Фудзивара (пиридин, щёлочь, нагревание) — красный цвет; жидкость Фелинга при нагревании — сначала жёлтый, затем красный осадок (реагируют хлороформ и хлоралгидрат, четырёххлористый углерод и дихлорэтан нет)."),
            "TOKS", loc("TOKS", pdf=36, to=37), "presumptive", "presumptive", reagents=["alkaline resorcinol", "Fehling solution"],
            note=N("The source gives the silver nitrate reaction a negative value; the group reactions can confuse chloroform with chloral hydrate and formaldehyde.",
                   "Manba kumush nitrat reaksiyasiga manfiy ahamiyat beradi; guruh reaksiyalari xloroformni xloralgidrat va formaldegid bilan chalkashtirishi mumkin.",
                   "Источник придаёт реакции с нитратом серебра отрицательное значение; групповые реакции могут приводить к путанице хлороформа с хлоралгидратом и формальдегидом.")))

# =============================================================== GASES / CYANIDE
add(colour("hydrogen-cyanide", "prussian", ["blue"], "TOKS", loc("TOKS", pdf=29), kind="chemical",
           note=N("First distillate collected into 2% sodium hydroxide; iron(II) sulfate is added, the mixture is heated, cooled and acidified with hydrochloric acid; a blue solution or precipitate (Prussian blue) indicates cyanide. If no colour appears, the tube is left for 48 hours before a conclusion is drawn (laboratory work, PDF pp. 173–174). The source calls this a specific reaction for hydrogen cyanide; a negative result may not exclude exposure, because cyanide can decompose or be converted in the body.",
                  "Birinchi distillyat 2% natriy ishqori eritmasiga yig‘iladi; temir(II) sulfat qo‘shiladi, aralashma qizdiriladi, sovitiladi va xlorid kislota bilan nordonlashtiriladi; ko‘k eritma yoki cho‘kma (Berlin zangorisi) sianidni ko‘rsatadi. Rang chiqmasa, xulosa chiqarishdan oldin probirka 48 soatga qoldiriladi (laboratoriya mashg‘uloti, PDF 173–174-betlar). Manba buni vodorod sianid uchun xos reaksiya deb ataydi; manfiy natija ta’sirni istisno qilmasligi mumkin, chunki sianid organizmda parchalanishi yoki o‘zgarishi mumkin.",
                  "Первый дистиллят собирают в 2% гидроксид натрия; добавляют сульфат железа(II), нагревают, охлаждают и подкисляют соляной кислотой; синий раствор или осадок (берлинская лазурь) указывает на цианид. Если окраска не появилась, пробирку оставляют на 48 часов, прежде чем делать вывод (лабораторная работа, PDF сс. 173–174). Источник называет это специфичной реакцией на циановодород; отрицательный результат может не исключать воздействие, так как цианид может разлагаться или превращаться в организме."),
           tag="presumptive"))
add(generic("hydrogen-sulfide", "chemical",
            N("A small volume of the aqueous test solution is warmed in a flask with a strip of lead acetate paper held above it; blackening of the paper (lead sulfide) indicates hydrogen sulfide. The source adds that hydrogen sulfide in a biological specimen shows that putrefaction is under way, which matters for the interpretation (ammonia and hydrogen sulfide form together).",
              "Tekshiriluvchi suvli eritmaning oz hajmi kolbada isitiladi, uning ustida qo‘rg‘oshin atsetat qog‘ozi ushlab turiladi; qog‘ozning qorayishi (qo‘rg‘oshin sulfid) vodorod sulfidni ko‘rsatadi. Manba biologik ob’ektda vodorod sulfid topilishi chirish jarayoni ketayotganini ko‘rsatishini qo‘shimcha qiladi, bu talqin uchun muhim (ammiak va vodorod sulfid birga hosil bo‘ladi).",
              "Небольшой объём водного исследуемого раствора нагревают в колбе, над которой удерживают полоску бумаги с ацетатом свинца; почернение бумаги (сульфид свинца) указывает на сероводород. Источник добавляет, что сероводород в биологическом объекте показывает идущее гниение, что важно для интерпретации (аммиак и сероводород образуются вместе)."),
            "TOKS", loc("TOKS", pdf=147), "presumptive", "presumptive", recipes=["recipe-lead-acetate-paper"], reagents=["lead acetate paper"]))
add(generic("phosphine", "chemical",
            N("Described for zinc phosphide poisoning: phosphine is released by acidifying the specimen with sulfuric acid and steam distillation, collected in bromine water, where it is oxidised to phosphoric acid; the phosphate is then shown with ammonium molybdate (yellow phosphomolybdate precipitate) and a reducing agent (blue colour). The source does not describe this procedure for aluminium phosphide. The molybdenum blue reaction is given by any phosphate, so it supports but does not identify phosphine.",
              "Rux fosfidi bilan zaharlanish uchun tavsiflangan: fosfin ob’ektni sulfat kislota bilan nordonlashtirish va suv bug‘i bilan haydash orqali ajratiladi, bromli suvga yig‘iladi va u yerda fosfat kislotagacha oksidlanadi; fosfat ammoniy molibdat (sariq fosformolibdat cho‘kmasi) va qaytaruvchi (ko‘k rang) bilan aniqlanadi. Manba bu usulni alyuminiy fosfid uchun tavsiflamaydi. Molibden ko‘ki reaksiyasini har qanday fosfat beradi, shuning uchun u fosfinni aniqlamaydi, faqat qo‘llab-quvvatlaydi.",
              "Описано для отравления фосфидом цинка: фосфин выделяют подкислением объекта серной кислотой и перегонкой с водяным паром, собирают в бромную воду, где он окисляется до фосфорной кислоты; фосфат затем показывают молибдатом аммония (жёлтый осадок фосфомолибдата) и восстановителем (синий цвет). Для фосфида алюминия источник эту процедуру не описывает. Реакцию молибденовой сини даёт любой фосфат, поэтому она поддерживает, но не идентифицирует фосфин."),
            "TOKS", loc("TOKS", pdf=70, to=71), "supporting", "supporting",
            recipes=["recipe-bromine-water", "recipe-ammonium-molybdate-solution"], reagents=["bromine water", "ammonium molybdate"]))
add(generic("carbon-monoxide", "spectroscopy",
            N("Blood examined with a hand spectroscope: carboxyhaemoglobin shows two absorption bands (564–579 nm and 523–536 nm) that, unlike oxyhaemoglobin, do not merge into one broad band on adding a reducing agent (ammonium sulfide). Spectrophotometry in the 450–620 nm range after reduction with sodium dithionite: deoxyhaemoglobin has one maximum (557 nm), carboxyhaemoglobin two (541 and 571 nm), with isosbestic points at 550, 565 and 580 nm.",
              "Qonni spektroskop bilan tekshirish: karboksigemoglobin ikkita yutilish yo‘li beradi (564–579 nm va 523–536 nm); oksigemoglobindan farqli o‘laroq, qaytaruvchi (ammoniy sulfid) qo‘shilganda ular bitta keng yo‘lga qo‘shilmaydi. Natriy ditionit bilan qaytarilgandan keyin 450–620 nm sohada spektrofotometriya: dezoksigemoglobinda bitta maksimum (557 nm), karboksigemoglobinda ikkita (541 va 571 nm), izobestik nuqtalar 550, 565 va 580 nm da.",
              "Исследование крови ручным спектроскопом: карбоксигемоглобин даёт две полосы поглощения (564–579 нм и 523–536 нм), которые, в отличие от оксигемоглобина, не сливаются в одну широкую полосу при добавлении восстановителя (сульфида аммония). Спектрофотометрия в области 450–620 нм после восстановления дитионитом натрия: дезоксигемоглобин имеет один максимум (557 нм), карбоксигемоглобин два (541 и 571 нм), изобестические точки при 550, 565 и 580 нм."),
            "TOKS", loc("TOKS", pdf=83, to=84), "supporting", "supporting", cat=None,
            recipes=["recipe-phosphate-buffer-ph-7-38"], reagents=["sodium dithionite", "ammonium sulfide"],
            note=N("The existing COHb guideline card lists the limitations of optical methods (other haemoglobin pigments, heated or putrefied blood).",
                   "Mavjud COHb yo‘riqnoma kartasi optik usullarning cheklovlarini keltiradi (boshqa gemoglobin pigmentlari, qizdirilgan yoki chirigan qon).",
                   "Существующая карточка руководства по COHb перечисляет ограничения оптических методов (другие пигменты гемоглобина, нагретая или гнилостная кровь).")))

# =============================================================== METALS / STRYCHNINE
add(generic("arsenic-trioxide", "chemical",
            N("Mineralisate tests: Sanger–Black (arsine from digest, tin(II) chloride and copper-coated zinc, lead acetate cotton against hydrogen sulfide) — a yellow to brown spot on mercury(II) bromide paper; silver diethyldithiocarbamate in pyridine — red or pink colour with arsine; Marsh test — reagent blank first, then a shiny black mirror in the narrow tube, a bluish flame, a garlic odour and a brown-grey deposit on a cold porcelain dish; the mirror dissolves in hypochlorite (antimony does not) and on heating in air gives octahedral crystals of the oxide. The source gives the Sanger–Black reaction a negative value: if it is negative the examination for arsenic stops, if positive the Marsh test is obligatory.",
              "Mineralizatdagi sinamalar: Zanger–Blek (mineralizat, qalay(II) xlorid va mislangan ruxdan arsin, vodorod sulfidga qarshi qo‘rg‘oshin atsetatli paxta) — simob(II) bromid qog‘ozida sariqdan qo‘ng‘irgacha dog‘; kumush dietilditiokarbamatning piridindagi eritmasi — arsin bilan qizil yoki pushti rang; Marsh sinamasi — avval reaktivlar nazorati, so‘ng tor naychada yaltiroq qora ko‘zgu, ko‘kimtir alanga, sarimsoq hidi va sovuq chinni idishda qo‘ng‘ir-kulrang dog‘; ko‘zgu gipoxloritda eriydi (surma erimaydi) va havoda qizdirilganda oksidning sakkiz qirrali kristallarini beradi. Manba Zanger–Blek reaksiyasiga manfiy ahamiyat beradi: u manfiy bo‘lsa, mishyakka tekshirish to‘xtatiladi, musbat bo‘lsa Marsh sinamasi majburiy.",
              "Пробы с минерализатом: Зангер—Блэк (арсин из минерализата, хлорида олова(II) и омеднённого цинка, вата с ацетатом свинца против сероводорода) — жёлтое или коричневое пятно на бумаге с бромидом ртути(II); диэтилдитиокарбамат серебра в пиридине — красный или розовый цвет с арсином; проба Марша — сначала контроль реактивов, затем блестящее чёрное зеркало в узкой части трубки, синеватое пламя, чесночный запах и коричнево-серый налёт на холодной фарфоровой чашке; зеркало растворяется в гипохлорите (сурьмяное нет) и при нагревании на воздухе даёт октаэдрические кристаллы оксида. Источник придаёт реакции Зангера—Блэка отрицательное значение: при отрицательном результате исследование на мышьяк прекращают, при положительном проба Марша обязательна."),
            "TOKS", loc("TOKS", pdf=75, to=77), "presumptive", "presumptive",
            recipes=["recipe-mercury-halide-paper", "recipe-lead-acetate-cotton", "recipe-cuprated-zinc", "recipe-tin-ii-chloride-solution",
                     "recipe-silver-diethyldithiocarbamate-pyridine"],
            reagents=["mercury(II) bromide paper", "silver diethyldithiocarbamate", "Marsh apparatus"]))
add(generic("thallium-sulfate", "chemical",
            N("Mineralisate tests: malachite green (or brilliant green) with sulfuric acid, hydrochloric acid and sodium nitrite extracted into toluene — blue toluene layer (blue ion associate), which antimony also gives; thallium(I) dithizonate after masking (citric acid, thiourea, hydroxylamine, potassium cyanide, ammonia, pH 11–13) — the chloroform layer is coloured (dark red in the lecture text, bluish-violet in the laboratory-work text; the two passages differ). The source states that thallium and antimony cannot be told apart by the malachite green reaction alone.",
              "Mineralizatdagi sinamalar: malaxit yashili (yoki brilliant yashili), sulfat kislota, xlorid kislota va natriy nitrit toluolga ekstraksiya qilinadi — toluol qatlami ko‘k (ko‘k ion assotsiati), uni surma ham beradi; niqoblashdan keyin talliy(I) ditizonati (limon kislota, tiomochevina, gidroksilamin, kaliy sianid, ammiak, pH 11–13) — xloroform qatlami bo‘yaladi (ma’ruza matnida to‘q qizil, laboratoriya mashg‘uloti matnida ko‘kimtir-binafsha; ikki band farq qiladi). Manba talliy va surmani faqat malaxit yashili reaksiyasi bilan farqlab bo‘lmasligini bildiradi.",
              "Пробы с минерализатом: малахитовый зелёный (или бриллиантовый зелёный) с серной кислотой, соляной кислотой и нитритом натрия, экстракция в толуол — синий толуольный слой (синий ионный ассоциат), его даёт и сурьма; дитизонат таллия(I) после маскирования (лимонная кислота, тиомочевина, гидроксиламин, цианид калия, аммиак, pH 11–13) — окрашивается хлороформный слой (тёмно-красный в тексте лекции, синевато-фиолетовый в тексте лабораторной работы; два места различаются). Источник указывает, что таллий и сурьму нельзя различить только по реакции с малахитовым зелёным."),
            "TOKS", loc("TOKS", pdf=67, to=68), "presumptive", "presumptive", recipes=["recipe-dithizone-solution"],
            reagents=["malachite green", "dithizone"],
            note=N("The laboratory-work text is on PDF pp. 207–208.", "Laboratoriya mashg‘uloti matni PDF 207–208-betlarda.",
                   "Текст лабораторной работы — на PDF сс. 207–208.")))
add(colour("strychnine", ["k2cr2o7_h2so4"], ["violet"], "TOKS", loc("TOKS", pdf=107), timing=None, kind="chemical",
           note=N("The violet colour disappears quickly; brucine interferes, so brucine is first destroyed with concentrated sulfuric and nitric acids. With Mandelin reagent strychnine gives a blue-violet compound turning red; it also gives the Vitali–Morin reaction. The source adds a pharmacological test (tetanic spasms in a frog).",
                  "Binafsha rang tez yo‘qoladi; brutsin halaqit beradi, shuning uchun brutsin avval konsentrlangan sulfat va nitrat kislotalar bilan parchalanadi. Mandelin reaktivi bilan strixnin qizilga o‘tuvchi ko‘k-binafsha birikma hosil qiladi; u Vitali–Moren reaksiyasini ham beradi. Manba farmakologik sinamani ham keltiradi (baqada tetanik tirishish).",
                  "Фиолетовая окраска быстро исчезает; мешает бруцин, поэтому бруцин предварительно разрушают концентрированными серной и азотной кислотами. С реактивом Манделина стрихнин даёт сине-фиолетовое соединение, переходящее в красное; он даёт и реакцию Витали—Морена. Источник добавляет фармакологическую пробу (тетанические судороги у лягушки)."),
           tag="presumptive"))

# =============================================================== ORGANOPHOSPHORUS PESTICIDES
add(generic("malathion", "chemical",
            N("Residue of a benzene extract (acidified to pH 1): diazotised sulfanilic acid with alkali — dark red colour; Marquis reagent — first a pale (rock-candy, «novvot») tint slowly turning dark brown; copper sulfate in alkaline medium at pH 4–5 — chloroform layer blue-yellow («possible» malathion); mercury(II) chloride — star-shaped microcrystals; bismuth iodide — dark-red needle microcrystals; iodine monochloride — brown crystals that lose their shape with time.",
              "Benzolli ekstrakt qoldig‘i (pH 1 gacha nordonlashtirilgan): diazotirlangan sulfanil kislota va ishqor — to‘q qizil rang; Marki reaktivi — avval och (novvot) tus, u sekin to‘q qo‘ng‘irga o‘tadi; ishqoriy muhitda pH 4–5 da mis sulfat — xloroform qatlami ko‘k-sariq («bo‘lishi mumkin»); simob(II) xlorid — yulduzsimon mikrokristallar; vismut yodid — to‘q qizil ninasimon mikrokristallar; yod-monoxlorid — vaqt o‘tishi bilan shaklini yo‘qotadigan qo‘ng‘ir kristallar.",
              "Остаток бензольного извлечения (подкисленного до pH 1): диазотированная сульфаниловая кислота со щёлочью — тёмно-красный цвет; реактив Марки — сначала бледная («новвот», леденцовая) окраска, медленно переходящая в тёмно-коричневую; сульфат меди в щелочной среде при pH 4–5 — хлороформный слой сине-жёлтый («возможно» малатион); хлорид ртути(II) — звёздчатые микрокристаллы; иодид висмута — тёмно-красные игольчатые микрокристаллы; монохлорид иода — коричневые кристаллы, теряющие форму со временем."),
            "TOKS", loc("TOKS", pdf=265, to=266), "presumptive", "presumptive",
            recipes=["recipe-diazotised-sulfanilic-acid", "recipe-marquis"], reagents=["diazotised sulfanilic acid", "Marquis reagent"],
            note=N("The source names the compound karbofos (malathion).", "Manba birikmani karbofos (malation) deb ataydi.",
                   "Источник называет соединение карбофос (малатион).")))
add(tlc("malathion", [("hexane", 10), ("Et2O", 2)], "not_stated", "bromophenol_acetic", "TOKS", loc("TOKS", pdf=266),
        rf=[(None, "0.60–0.65")],
        note=N("Plate coated and developed to 10 cm; the plate is sprayed first with bromophenol blue reagent and after 10 minutes with 5% acetic acid: malathion and some of its metabolites give blue-green spots on a yellow plate. The source does not state the sorbent.",
               "Plastinka 10 sm gacha yurgiziladi; plastinka avval bromfenol ko‘ki reaktivi, 10 daqiqadan keyin 5% sirka kislota bilan purkaladi: sariq plastinkada karbofos va uning ayrim metabolitlari ko‘k-zangori dog‘ beradi. Manba sorbentni ko‘rsatmaydi.",
               "Пластинку хроматографируют до 10 см; сначала опрыскивают реактивом бромфеноловым синим, через 10 минут — 5% уксусной кислотой: малатион и некоторые его метаболиты дают сине-зелёные пятна на жёлтом фоне. Сорбент в источнике не указан.")))
OP = ["malathion", "chlorpyrifos", "diazinon", "parathion"]
add(generic(OP, "chemical",
            N("Class-level screening for organophosphorus compounds (the source describes it for the class and does not name this substance): after mineralisation, ammonium molybdate gives a yellow phosphomolybdate that a reductant turns blue (molybdenum blue); cholinesterase inhibition shown by unhydrolysed acetylcholine (red iron hydroxamate complex) or an indicator change. The source gives both tests a negative value: any phosphorus compound gives molybdenum blue, and carbamates (for example carbaryl), neostigmine, galantamine, alcohol and protein breakdown products interfere with the cholinesterase test.",
              "Fosfororganik birikmalar uchun sinf darajasidagi skrining (manba buni sinf uchun tavsiflaydi va bu moddani nomlamaydi): mineralizatsiyadan keyin ammoniy molibdat sariq fosformolibdat beradi, qaytaruvchi uni ko‘k (molibden ko‘ki) ga o‘tkazadi; xolinesterazaning ingibirlanishi gidrolizlanmagan atsetilxolin (qizil temir gidroksamat kompleksi) yoki indikator rangining o‘zgarishi bilan ko‘rsatiladi. Manba ikkala sinamaga manfiy ahamiyat beradi: har qanday fosfor saqlovchi modda molibden ko‘kini beradi, xolinesteraza sinamasiga esa karbamatlar (masalan, karbaril), neostigmin, galantamin, spirt va oqsillarning parchalanish mahsulotlari halaqit beradi.",
              "Групповой скрининг фосфорорганических соединений (источник описывает его для класса и не называет это вещество): после минерализации молибдат аммония даёт жёлтый фосфомолибдат, который восстановитель окрашивает в синий цвет (молибденовая синь); ингибирование холинэстеразы показывают по негидролизованному ацетилхолину (красный гидроксаматный комплекс железа) или по изменению цвета индикатора. Источник придаёт обеим пробам отрицательное значение: молибденовую синь даёт любое соединение фосфора, а определению по холинэстеразе мешают карбаматы (например, карбарил), неостигмин, галантамин, спирт и продукты распада белков."),
            "TOKS", loc("TOKS", pdf=153, to=154), "presumptive", "presumptive",
            recipes=["recipe-ammonium-molybdate-solution"], reagents=["ammonium molybdate"], data={"scope": "class"}))
add(tlc_free(OP,
             N("Class-level TLC type assignment (the source describes it for the class): the extract is spotted four times on one plate and developed in water-saturated chloroform; the four zones are sprayed separately with bromophenol blue and acetic acid (blue spots on a yellow background: thio- and dithiophosphates), sodium hydroxide (yellow: compounds with a p-nitrophenol moiety), Dragendorff reagent (brown: octamethyl and some nitrogen-containing compounds) and alkaline resorcinol (red: trichlorfon). The spot colours and Rf are compared with tabulated values of the listed organophosphorus compounds before targeted analysis; the source does not tabulate this substance in the passage cited.",
               "Sinf darajasidagi TLC yordamida tur aniqlash (manba buni sinf uchun tavsiflaydi): ajralma bir plastinkaga to‘rt nuqta qilib tomiziladi va suv bilan to‘yingan xloroformda yurgiziladi; to‘rt zona alohida purkaladi: bromfenol ko‘ki va sirka kislota (sariq fonda ko‘k dog‘lar: tio- va ditiofosfatlar), natriy ishqori (sariq: paranitrofenol qoldig‘i saqlovchi birikmalar), Dragendorf reaktivi (qo‘ng‘ir: oktametil va ayrim azot saqlovchi birikmalar) va ishqoriy rezorsin (qizil: xlorofos). Maqsadli tahlildan oldin dog‘ ranglari va Rf sanab o‘tilgan fosfororganik birikmalarning jadval qiymatlari bilan taqqoslanadi; manba keltirilgan bandda bu modda uchun jadval bermaydi.",
               "Групповое определение типа соединения методом TLC (источник описывает его для класса): экстракт наносят четырьмя пятнами на одну пластинку и хроматографируют в насыщенном водой хлороформе; четыре зоны опрыскивают отдельно бромфеноловым синим и уксусной кислотой (синие пятна на жёлтом фоне: тио- и дитиофосфаты), гидроксидом натрия (жёлтый: соединения с остатком п-нитрофенола), реактивом Драгендорфа (коричневый: октаметил и некоторые азотсодержащие соединения) и щелочным резорцином (красный: трихлорфон). Цвета пятен и Rf сравнивают с табличными значениями перечисленных фосфорорганических соединений до целевого анализа; в цитируемом месте источник не приводит таблицу для этого вещества."),
             "TOKS", loc("TOKS", pdf=154, to=155), data={"scope": "class"}))
