// GENERATED by tool/update_bundled_pack.sh — qo‘lda o‘zgartirmang.
//
// Faqat OCHIQ kalit. Development kanal kaliti har yig‘ishda yangilanadi;
// production kaliti alohida (RG-17) va bu faylga hech qachon tushmaydi.

/// Ilovaga o‘rnatilgan pilot paketni tekshiruvchi ochiq kalitlar.
const bundledPackTrustedKeys = <String, String>{
  'development-a9731ef7c956': 'hRj/z1cc1hCpuxEurNv4y491nvetI87Mw6e/EKLMZwU=',
};
