// GENERATED by tool/update_bundled_pack.sh — qo‘lda o‘zgartirmang.
//
// Faqat OCHIQ kalit. Development kanal kaliti har yig‘ishda yangilanadi;
// production kaliti alohida (RG-17) va bu faylga hech qachon tushmaydi.

/// Ilovaga o‘rnatilgan pilot paketni tekshiruvchi ochiq kalitlar.
const bundledPackTrustedKeys = <String, String>{
  'development-079a22c14827': 'zCQJHcteSCbtPml0OOmeBzoiZr9TQ0pWaD7Sg/MAINE=',
};
