// GENERATED by tool/update_bundled_pack.sh — qo‘lda o‘zgartirmang.
//
// Faqat OCHIQ kalit. Development kanal kaliti har yig‘ishda yangilanadi;
// production kaliti alohida (RG-17) va bu faylga hech qachon tushmaydi.

/// Ilovaga o‘rnatilgan pilot paketni tekshiruvchi ochiq kalitlar.
const bundledPackTrustedKeys = <String, String>{
  'development-f3cb2dfc2352': 'uXngoMxSGX0S3Dly0NggSdLEZGImybPA/+/s1O5iNI4=',
};
